#!/bin/bash
# generated by sweep_make.py; run from the repository root on GRACE
set -e
mkdir -p slurm_logs
JOBS=""
J=$(sbatch --parsable --job-name=sw_0.500 --time=12:00:00 --array=0-4 --export=ALL,CASE=cases/sweep_plating_j0_A100/f_0.500,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_0.500"
JOBS="$JOBS:$J"
J=$(sbatch --parsable --job-name=sw_0.750 --time=12:00:00 --array=0-4 --export=ALL,CASE=cases/sweep_plating_j0_A100/f_0.750,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_0.750"
JOBS="$JOBS:$J"
J=$(sbatch --parsable --job-name=sw_1.000 --time=12:00:00 --array=0-4 --export=ALL,CASE=cases/sweep_plating_j0_A100/f_1.000,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_1.000"
JOBS="$JOBS:$J"
J=$(sbatch --parsable --job-name=sw_1.250 --time=12:00:00 --array=0-4 --export=ALL,CASE=cases/sweep_plating_j0_A100/f_1.250,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_1.250"
JOBS="$JOBS:$J"
J=$(sbatch --parsable --job-name=sw_1.500 --time=12:00:00 --array=0-4 --export=ALL,CASE=cases/sweep_plating_j0_A100/f_1.500,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_1.500"
JOBS="$JOBS:$J"
sbatch --job-name=sw_analyze --dependency=afterany${JOBS} --export=ALL,SWEEP=cases/sweep_plating_j0_A100 slurm/sweep_analyze.slrm
echo "analysis job queued after${JOBS}"
