#!/bin/bash
# generated by sweep_make.py; run from the repository root on GRACE
set -e
mkdir -p slurm_logs
JOBS=""
J=$(sbatch --parsable --job-name=sw_0.500 --time=04:00:00 --array=0-9 --export=ALL,CASE=cases/sweep_plating_j0/f_0.500,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_0.500"
JOBS="$JOBS:$J"
J=$(sbatch --parsable --job-name=sw_0.625 --time=04:00:00 --array=0-9 --export=ALL,CASE=cases/sweep_plating_j0/f_0.625,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_0.625"
JOBS="$JOBS:$J"
J=$(sbatch --parsable --job-name=sw_0.750 --time=04:00:00 --array=0-9 --export=ALL,CASE=cases/sweep_plating_j0/f_0.750,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_0.750"
JOBS="$JOBS:$J"
J=$(sbatch --parsable --job-name=sw_0.875 --time=04:00:00 --array=0-9 --export=ALL,CASE=cases/sweep_plating_j0/f_0.875,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_0.875"
JOBS="$JOBS:$J"
J=$(sbatch --parsable --job-name=sw_1.000 --time=04:00:00 --array=0-9 --export=ALL,CASE=cases/sweep_plating_j0/f_1.000,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_1.000"
JOBS="$JOBS:$J"
J=$(sbatch --parsable --job-name=sw_1.125 --time=04:00:00 --array=0-9 --export=ALL,CASE=cases/sweep_plating_j0/f_1.125,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_1.125"
JOBS="$JOBS:$J"
J=$(sbatch --parsable --job-name=sw_1.250 --time=04:00:00 --array=0-9 --export=ALL,CASE=cases/sweep_plating_j0/f_1.250,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_1.250"
JOBS="$JOBS:$J"
J=$(sbatch --parsable --job-name=sw_1.375 --time=04:00:00 --array=0-9 --export=ALL,CASE=cases/sweep_plating_j0/f_1.375,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_1.375"
JOBS="$JOBS:$J"
J=$(sbatch --parsable --job-name=sw_1.500 --time=04:00:00 --array=0-9 --export=ALL,CASE=cases/sweep_plating_j0/f_1.500,BASE_SEED=8597 slurm/goKMC_prod_array.slrm)
echo "submitted $J for f_1.500"
JOBS="$JOBS:$J"
sbatch --job-name=sw_analyze --dependency=afterany${JOBS} --export=ALL,SWEEP=cases/sweep_plating_j0 slurm/sweep_analyze.slrm
echo "analysis job queued after${JOBS}"
